version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3080:3080
    volumes:
      - next_data:/data/next
      - ./content:/app/fe/content
      - ./public:/app/fe/public

volumes:
  next_data:
